name: smos-report
version: 0.8.1
category: Smos
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
license: MIT

dependencies:
- base

library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
  - aeson
  - autodocodec
  - autodocodec-yaml
  - conduit
  - containers
  - cursor
  - deepseq
  - envparse
  - hashable
  - megaparsec
  - microlens
  - optparse-applicative
  - parsec
  - path
  - path-io
  - pretty-show
  - safe
  - smos-data
  - text
  - time
  - validity
  - validity-path
  - validity-time
  - yaml
