name: smos-report
version: 0.9.0
category: Smos
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
license: MIT

dependencies:
- base

library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
  - aeson
  - autodocodec
  - conduit
  - containers
  - cursor
  - deepseq
  - envparse
  - hashable
  - megaparsec
  - microlens
  - optparse-applicative
  - parsec
  - path
  - path-io
  - pretty-show
  - safe
  - smos-data
  - text
  - time
  - tz
  - validity
  - validity-path
  - validity-time
  - yaml

tests:
  smos-report-dummy-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

