name: smos-scheduler
version: 0.7.0
category: Smos
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
license: MIT
  
extra-source-files:
- test_resources/**

dependencies:
- base

library:
  source-dirs: src/
  ghc-options: -Wall
  build-tools: autoexporter
  dependencies:
    - aeson
    - autodocodec
    - bytestring
    - conduit
    - containers
    - cron
    - envparse
    - fuzzy-time
    - hashable
    - megaparsec
    - mtl
    - optparse-applicative
    - path
    - path-io
    - pretty-relative-time
    - safe
    - safe-coloured-text
    - safe-coloured-text-terminfo
    - smos-cli
    - smos-data
    - smos-directory
    - smos-report
    - text
    - time
    - tz
    - unliftio
    - validity
    - validity-path
    - validity-text
    - yaml

executables:
  smos-scheduler:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - smos-scheduler

tests:
  smos-scheduler-test:
    main: Spec.hs
    source-dirs: test/
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - autodocodec
    - autodocodec-yaml
    - containers
    - cron
    - dirforest
    - genvalidity
    - genvalidity-containers
    - genvalidity-path
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-text
    - genvalidity-time
    - mtl
    - path
    - path-io
    - smos-cli
    - smos-data
    - smos-data-gen
    - smos-directory
    - smos-directory-gen
    - smos-report
    - smos-report-gen
    - smos-scheduler
    - sydtest
    - text
    - time
    - tz
