# DO NOT EDIT THIS FILE DIRECTLY
# This file was generated by
# smos-single:test/Smos/Single/OptParseSpec.hs:13
# To update this it, run the test with --golden-reset
{ lib }:
{
  workflow-dir = lib.mkOption {
    default = null;
    description = "The workflow directory";
    type = lib.types.nullOr lib.types.str;
  };
}
