name: smos-single
version: 0.4.0
category: Smos
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
license: MIT

extra-source-files:
- documentation.txt
- options.nix

dependencies:
- base

library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
    - opt-env-conf
    - path
    - path-io
    - smos-cli
    - smos-data
    - smos-directory
    - text
    - time

executables:
  smos-single:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - smos-single

tests:
  smos-single-test:
    main: Spec.hs
    source-dirs: test/
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - sydtest
    - smos-single
    - opt-env-conf-test
