name: smos-single
version: 0.3.0
category: Smos
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
license: MIT

library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
    - base
    - envparse
    - optparse-applicative
    - path
    - path-io
    - smos-cli
    - smos-data
    - smos-directory
    - text
    - time
    - autodocodec

executables:
  smos-single:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - base
    - smos-single
