resolver: lts-21.22
packages:
- smos
- smos-e2e
- smos-data
- smos-data-gen
- smos-cursor
- smos-cursor-gen
- smos-directory
- smos-directory-gen
- smos-report
- smos-report-gen
- smos-report-cursor
- smos-report-cursor-gen
- smos-query
- smos-single
- smos-scheduler
- smos-archive
- smos-calendar-import
- smos-docs-site
- smos-api
- smos-api-gen
- smos-server
- smos-server-gen
- smos-client
- smos-sync-client
- smos-sync-client-gen
- smos-web-style
- smos-web-server
- smos-cli
- smos-notify
- smos-github
- smos-jobhunt

- smos-stripe-client

# These are duplicated in nix/overlay.
ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef -O0 -Wunused-packages
  smos-stripe-client: -w # Turn off warnings for the generated code.

extra-deps:
- vty-6.2@sha256:3536dc83a3fee17d9a114baf58fe47b6f080c24987266f0cd0b7b4b1fcd9cf19,3520
- brick-2.3.1
- vty-crossplatform-0.4.0.0
- vty-unix-0.2.0.0@sha256:2af3d0bdae3c4b7b7e567ee374efe32c7439fabdf9096465ce011a6c6736e9ae,2932
- vty-windows-0.2.0.1@sha256:6c75230057a708168dbc420975572511ad3ec09956bf73c3b6f4be03324e8b13,2815

- github: NorfairKing/servant
  commit: 552da96ff9a6d81a8553c6429843178d78356054
  subdirs:
  - servant
  - servant-auth/servant-auth
  - servant-auth/servant-auth-client
  - servant-auth/servant-auth-server
  - servant-client
  - servant-client-core
  - servant-server

- github: NorfairKing/conformance
  commit: 2c236fd28c4cef63cd40d04631c5462d1df37759
  subdirs:
  - conformance
  - conformance-gen

- github: NorfairKing/ical
  commit: 34acdf5e6df3aa1a3fdeb96e2870af179177d6da
  subdirs:
  - ical
  - ical-gen
  - ical-recurrence
  - ical-recurrence-gen

- github: NorfairKing/typed-uuid
  commit: 00fbc7e0380ab2ff72e8fd02323e76f13b7d5b59
  subdirs:
  - typed-uuid
  - genvalidity-typed-uuid

- github: NorfairKing/mergeful
  commit: 30812d2cd9ca71ea3716b89dbd8820502856706c
  subdirs:
    - mergeful
    - mergeful-persistent
    - genvalidity-mergeful
  
- github: NorfairKing/looper
  commit: 90287d7c9468a64510831738c0c82ad9f493473f
  subdirs:
    - looper
  
- github: NorfairKing/pretty-relative-time
  commit: e3a97eea9539b22deb1e44405eb2d909866fa6f3

- github: NorfairKing/cursor-fuzzy-time
  commit: a73267b5ae91824538f3d1230e2e59cbee88af7a
  subdirs:
    - cursor-fuzzy-time
    - cursor-fuzzy-time-gen
  
- github: NorfairKing/fuzzy-time
  commit: a0966a82eea64afaa165f42ef258ec2052ec97be
  subdirs:
    - fuzzy-time
    - fuzzy-time-gen

- github: NorfairKing/dirforest
  commit: afa8b27feaabdfd584ed3200d6cc53dab94b29aa
  subdirs:
    - dirforest
    - genvalidity-dirforest

- github: NorfairKing/cursor-dirforest
  commit: af4d9b313752021c5f7a220b35829638bca8ce93
  subdirs:
    - cursor-dirforest
    - cursor-dirforest-gen
    - cursor-dirforest-brick

- github: NorfairKing/cursor-brick
  commit: 7f682cdbf4d79c6aadd10a8141461f177dc8f027
  subdirs:
    - cursor-brick

- github: NorfairKing/cursor
  commit: 5f18d58d1b34a752d24a94590c2cd35e8b6d557b
  subdirs:
    - cursor
    - cursor-gen

- github: NorfairKing/autodocodec
  commit: f661ec72fd68ef40c1ae8b698e0411989abf8747
  subdirs:
    - autodocodec
    - autodocodec-yaml
    - autodocodec-schema

- github: NorfairKing/safe-coloured-text
  commit: f18578151d579c495eda46b8eeafcddb69adea07
  subdirs:
  - safe-coloured-text
  - safe-coloured-text-gen
  - safe-coloured-text-layout
  - safe-coloured-text-layout-gen
  - safe-coloured-text-terminfo

- github: NorfairKing/sydtest
  commit: dd1c2b9b39d0995c8581524e8b42b8ca1d0c427a
  subdirs:
    - sydtest
    - sydtest-aeson
    - sydtest-discover
    - sydtest-persistent
    - sydtest-persistent-sqlite
    - sydtest-servant
    - sydtest-wai
    - sydtest-yesod

- github: NorfairKing/validity
  commit: a251897dc1eb7e851fd4d3dbc6fa976d22388f27
  subdirs:
    - genvalidity
    - genvalidity-aeson
    - genvalidity-bytestring
    - genvalidity-case-insensitive
    - genvalidity-containers
    - genvalidity-criterion
    - genvalidity-hspec
    - genvalidity-hspec-aeson
    - genvalidity-hspec-binary
    - genvalidity-hspec-cereal
    - genvalidity-hspec-hashable
    - genvalidity-hspec-optics
    - genvalidity-hspec-persistent
    - genvalidity-network-uri
    - genvalidity-path
    - genvalidity-persistent
    - genvalidity-property
    - genvalidity-scientific
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-sydtest-hashable
    - genvalidity-sydtest-lens
    - genvalidity-sydtest-persistent
    - genvalidity-text
    - genvalidity-time
    - genvalidity-unordered-containers
    - genvalidity-uuid
    - genvalidity-vector
    - validity
    - validity-aeson
    - validity-bytestring
    - validity-case-insensitive
    - validity-containers
    - validity-network-uri
    - validity-path
    - validity-persistent
    - validity-primitive
    - validity-scientific
    - validity-text
    - validity-time
    - validity-unordered-containers
    - validity-uuid
    - validity-vector



 
- github: NorfairKing/yesod-static-remote
  commit: 7eda644dc369e16c3591847f6c7cad30846bf6b0

- github: NorfairKing/yesod-autoreload
  commit: 796def9af50cd7b053c9fb4a065c55603d4a8399

- github: NorfairKing/template-haskell-reload
  commit: c416550db3f353bad65980a8ecd9b3b81fa504bd
  subdirs:
    - template-haskell-reload

- github: brendanhay/amazonka
  commit: 9c3594073a7787e27f13fa14c936f0fa5cb9f0e8
  subdirs:
  - lib/amazonka
  - lib/amazonka-core
  - lib/amazonka-test
  - lib/services/amazonka-ses
  - lib/services/amazonka-sso
  - lib/services/amazonka-sts


flags:
  zip:
    disable-bzip2: true

system-ghc: true
nix:
  enable: false # We enter the shell manually.
with-hpack: hpack
