resolver: lts-19.32
packages:
- smos
- smos-data
- smos-data-gen
- smos-cursor
- smos-cursor-gen
- smos-directory
- smos-directory-gen
- smos-report
- smos-report-gen
- smos-report-cursor
- smos-report-cursor-gen
- smos-query
- smos-single
- smos-scheduler
- smos-archive
- smos-calendar-import
- smos-docs-site
- smos-api
- smos-api-gen
- smos-server
- smos-server-gen
- smos-client
- smos-sync-client
- smos-sync-client-gen
- smos-web-style
- smos-web-server
- smos-cli
- smos-notify
- smos-github
- smos-jobhunt

- smos-stripe-client

# These are duplicated in nix/overlay.
ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef -O0 -Wunused-packages
  smos-stripe-client: -w # Turn off warnings for the generated code.

extra-deps:
# Newer brick
- brick-1.6
- vty-5.38
- bimap-0.5.0@sha256:aba506d02a1c93fc2b50dcbe728d2a4d07cca89b7033945418061a0b08576ebd,1889
- text-zipper-0.13@sha256:e1a48d69c9324ed3784bc39d5ded84d63ea3115b32a018ddf76158ed9d58dc0a,1472

- github: NorfairKing/ical
  commit: 763e57dded8ed140b9b54360a7bdddd5ac28f1b9
  subdirs:
  - ical
  - ical-gen
  - ical-recurrence
  - ical-recurrence-gen

- github: NorfairKing/typed-uuid
  commit: 00fbc7e0380ab2ff72e8fd02323e76f13b7d5b59
  subdirs:
  - typed-uuid
  - genvalidity-typed-uuid

- github: NorfairKing/mergeful
  commit: 832092b8ed706bd3b045d5106f96715a6f4ddc4a
  subdirs:
    - mergeful
    - mergeful-persistent
    - genvalidity-mergeful
  
- github: NorfairKing/looper
  commit: 65975dd100b162bb1e297be69099ba3ce73d1862
  subdirs:
    - looper
  
- github: NorfairKing/pretty-relative-time
  commit: e3a97eea9539b22deb1e44405eb2d909866fa6f3

- github: NorfairKing/cursor-fuzzy-time
  commit: 86830e3c14e1ec054e4423742eb34d1c49f9b8b0
  subdirs:
    - cursor-fuzzy-time
    - cursor-fuzzy-time-gen
  
- github: NorfairKing/fuzzy-time
  commit: aa3412d157da89b9f21dcda92b5c91a53b36ddd1
  subdirs:
    - fuzzy-time
    - fuzzy-time-gen

- github: NorfairKing/dirforest
  commit: 76d09379fd8e58c6d5c7287aeddd5a2d3d281562
  subdirs:
    - dirforest
    - genvalidity-dirforest

- github: NorfairKing/cursor-dirforest
  commit: 6ad5b168e26eb4e647df9f007d812aaf59338d40
  subdirs:
    - cursor-dirforest
    - cursor-dirforest-gen
    - cursor-dirforest-brick

- github: NorfairKing/cursor-brick
  commit: 5c1d1306632403a3dc11ddeda10deee932c0b307
  subdirs:
    - cursor-brick

- github: NorfairKing/cursor
  commit: 5f18d58d1b34a752d24a94590c2cd35e8b6d557b
  subdirs:
    - cursor
    - cursor-gen

- github: NorfairKing/autodocodec
  commit: fa4d53e6c7694427c9d777b883fc446c4f3651b0
  subdirs:
    - autodocodec
    - autodocodec-yaml
    - autodocodec-schema

- github: NorfairKing/safe-coloured-text
  commit: f18578151d579c495eda46b8eeafcddb69adea07
  subdirs:
  - safe-coloured-text
  - safe-coloured-text-gen
  - safe-coloured-text-layout
  - safe-coloured-text-layout-gen
  - safe-coloured-text-terminfo

- github: NorfairKing/sydtest
  commit: dd1c2b9b39d0995c8581524e8b42b8ca1d0c427a
  subdirs:
    - sydtest
    - sydtest-aeson
    - sydtest-discover
    - sydtest-persistent
    - sydtest-persistent-sqlite
    - sydtest-servant
    - sydtest-wai
    - sydtest-yesod

- github: NorfairKing/validity
  commit: a251897dc1eb7e851fd4d3dbc6fa976d22388f27
  subdirs:
    - genvalidity
    - genvalidity-aeson
    - genvalidity-bytestring
    - genvalidity-case-insensitive
    - genvalidity-containers
    - genvalidity-criterion
    - genvalidity-hspec
    - genvalidity-hspec-aeson
    - genvalidity-hspec-binary
    - genvalidity-hspec-cereal
    - genvalidity-hspec-hashable
    - genvalidity-hspec-optics
    - genvalidity-hspec-persistent
    - genvalidity-network-uri
    - genvalidity-path
    - genvalidity-persistent
    - genvalidity-property
    - genvalidity-scientific
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-sydtest-hashable
    - genvalidity-sydtest-lens
    - genvalidity-sydtest-persistent
    - genvalidity-text
    - genvalidity-time
    - genvalidity-unordered-containers
    - genvalidity-uuid
    - genvalidity-vector
    - validity
    - validity-aeson
    - validity-bytestring
    - validity-case-insensitive
    - validity-containers
    - validity-network-uri
    - validity-path
    - validity-persistent
    - validity-primitive
    - validity-scientific
    - validity-text
    - validity-time
    - validity-unordered-containers
    - validity-uuid
    - validity-vector



 
- github: NorfairKing/yesod-static-remote
  commit: 7eda644dc369e16c3591847f6c7cad30846bf6b0

- github: NorfairKing/yesod-autoreload
  commit: 796def9af50cd7b053c9fb4a065c55603d4a8399

- github: NorfairKing/template-haskell-reload
  commit: c416550db3f353bad65980a8ecd9b3b81fa504bd
  subdirs:
    - template-haskell-reload

- github-0.27@sha256:2288b807a4bd97fefeff75487ef5d2ed31f0faa18f306e01e5f5cb498e228208,7033

- HaskellNet-0.6.0.1@sha256:061c503b5295e961cbe809b37305556a185ef99bc163d648c92870e3e2facca9,2376
- HaskellNet-SSL-0.3.4.4@sha256:6a1a3c6d3804e857d183e702214476a383628eac83eb4bcbc7d5c4b8a2e05bf3,1704

- github: brendanhay/amazonka
  commit: 2dc498fe75ff47db2db3ee63e042b1aa3da57c0f
  subdirs:
  - lib/amazonka
  - lib/amazonka-core
  - lib/amazonka-test
  - lib/services/amazonka-ses
  - lib/services/amazonka-sso
  - lib/services/amazonka-sts


flags:
  zip:
    disable-bzip2: true

system-ghc: true
with-hpack: hpack
nix:
  enable: false # We enter the shell manually.
