resolver: lts-24.38
packages:
- smos
- smos-e2e
- smos-data
- smos-data-gen
- smos-cursor
- smos-cursor-gen
- smos-directory
- smos-directory-gen
- smos-report
- smos-report-gen
- smos-report-cursor
- smos-report-cursor-gen
- smos-query
- smos-single
- smos-scheduler
- smos-archive
- smos-calendar-import
- smos-docs-site
- smos-api
- smos-api-gen
- smos-server
- smos-server-gen
- smos-client
- smos-sync
- smos-sync-gen
- smos-web-assets
- smos-web-server
- smos-cli
- smos-notify
- smos-github
- smos-jobhunt

- smos-stripe-client

# These are duplicated in nix/overlay.
ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef -O0 -Wunused-packages
  smos-stripe-client: -w # Turn off warnings for the generated code.

extra-deps:
- github: NorfairKing/prometheus-wai
  commit: 81e6d8c065ac7a4d80163f9947f9c3009e2f21da
  subdirs:
    - prometheus-wai
- github: NorfairKing/prometheus-ghc-stats
  commit: af03a7a84e184c878de7ffe30ca1a8b37ae1d210
  subdirs:
    - prometheus-ghc-stats

- github: NorfairKing/token-limiter-concurrent
  commit: 239fb2bbdf3f7ce6101788b24ad3ed0e6e6ae916
  subdirs:
    - token-limiter-concurrent

- github: NorfairKing/opt-env-conf
  commit: de7ac850e960c28e5182810515a87fbe1d6daede
  subdirs:
    - opt-env-conf
    - opt-env-conf-test

- github: NorfairKing/fast-myers-diff
  commit: 78ac171911bac6a9aafc2c9a642012c5a0e731f0
  subdirs:
    - fast-myers-diff

- github: NorfairKing/conformance
  commit: b9f82cb48f849452233caf9eaca76ea117f6252e
  subdirs:
  - conformance
  - conformance-gen

- github: NorfairKing/ical
  commit: b6b199c079358fc35c4e751e853233584e77e564
  subdirs:
  - ical
  - ical-gen
  - ical-recurrence
  - ical-recurrence-gen

- github: NorfairKing/typed-uuid
  commit: 00fbc7e0380ab2ff72e8fd02323e76f13b7d5b59
  subdirs:
  - typed-uuid
  - genvalidity-typed-uuid

- github: NorfairKing/mergeful
  commit: e9276fa9ffc3c8af4faa2f52d740ff3f63697ea8
  subdirs:
    - mergeful
    - mergeful-persistent
    - genvalidity-mergeful
  
- github: NorfairKing/looper
  commit: a48f7ce2c8067c14d0ad7ac549735962f19b066e
  subdirs:
    - looper
  
- github: NorfairKing/pretty-relative-time
  commit: e3a97eea9539b22deb1e44405eb2d909866fa6f3

- github: NorfairKing/cursor-fuzzy-time
  commit: c4a0a1e988dc01f8ddbb795a33c1ac42dd3a4aae
  subdirs:
    - cursor-fuzzy-time
    - cursor-fuzzy-time-gen
  
- github: NorfairKing/fuzzy-time
  commit: 3c935050db25bdc6d14c1b58976cdf55b0105f37
  subdirs:
    - fuzzy-time
    - fuzzy-time-gen

- github: NorfairKing/dirforest
  commit: 2aca5d03e3160b74d5b1e00ac8744541db143f8e
  subdirs:
    - dirforest
    - genvalidity-dirforest

- github: NorfairKing/cursor-dirforest
  commit: 350ca18233a50a7e4a9fdb216c02afd45237b14c
  subdirs:
    - cursor-dirforest
    - cursor-dirforest-gen
    - cursor-dirforest-brick

- github: NorfairKing/cursor-brick
  commit: 8d3ed58795434f8d05fd43dbba9670c571d8fd0a
  subdirs:
    - cursor-brick

- github: NorfairKing/cursor
  commit: f3f1bd0caff024cbae2afbfe57a721d77b36c9a7
  subdirs:
    - cursor
    - cursor-gen

- github: NorfairKing/autodocodec
  commit: 29b57dc2d425d732ce75143ecf3fc6411df0347b
  subdirs:
    - autodocodec
    - autodocodec-nix
    - autodocodec-schema
    - autodocodec-yaml


- github: NorfairKing/safe-coloured-text
  commit: 5d1187b7873a8a1e397245c7c0c6d9ab88765d67
  subdirs:
  - safe-coloured-text
  - safe-coloured-text-layout
  - safe-coloured-text-gen
  - safe-coloured-text-layout-gen
  - safe-coloured-text-terminfo

- github: NorfairKing/sydtest
  commit: 4c0b2699e4a3ded86dad312086f553ef45969820
  subdirs:
    - sydtest
    - sydtest-aeson
    - sydtest-discover
    - sydtest-persistent
    - sydtest-persistent-sqlite
    - sydtest-servant
    - sydtest-wai
    - sydtest-yesod
    - sydtest-mutation-runtime

- github: NorfairKing/validity
  commit: 456dfd9e4ef7906d33ce70f3f5fdf204a12cce8e
  subdirs:
    - genvalidity
    - genvalidity-aeson
    - genvalidity-bytestring
    - genvalidity-case-insensitive
    - genvalidity-containers
    - genvalidity-criterion
    - genvalidity-hspec
    - genvalidity-hspec-aeson
    - genvalidity-hspec-binary
    - genvalidity-hspec-cereal
    - genvalidity-hspec-hashable
    - genvalidity-hspec-optics
    - genvalidity-hspec-persistent
    - genvalidity-network-uri
    - genvalidity-path
    - genvalidity-persistent
    - genvalidity-property
    - genvalidity-scientific
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-sydtest-hashable
    - genvalidity-sydtest-lens
    - genvalidity-sydtest-persistent
    - genvalidity-text
    - genvalidity-time
    - genvalidity-unordered-containers
    - genvalidity-uuid
    - genvalidity-vector
    - validity
    - validity-aeson
    - validity-bytestring
    - validity-case-insensitive
    - validity-containers
    - validity-network-uri
    - validity-path
    - validity-persistent
    - validity-primitive
    - validity-scientific
    - validity-text
    - validity-time
    - validity-unordered-containers
    - validity-uuid
    - validity-vector



 
- github: NorfairKing/yesod-static-remote
  commit: 005d2458dba277a2eb4b572ce6c7aa585558dc62

- github: NorfairKing/yesod-autoreload
  commit: d0170f3a04756deaa5d9345f69f4769d02417a8d

- github: NorfairKing/template-haskell-reload
  commit: ff588f5f8d601743f477b12c961f41ca64a6dd2e
  subdirs:
    - template-haskell-reload

- github: brendanhay/amazonka
  commit: a7d699be1076e2aad05a1930ca3937ffea954ad8
  subdirs:
  - lib/amazonka
  - lib/amazonka-core
  - lib/amazonka-test
  - lib/services/amazonka-ses
  - lib/services/amazonka-sso
  - lib/services/amazonka-sts

- github: codedownio/HaskellNet
  commit: f91e223b1299e33c24fb3054e115629d53822f39
- HaskellNet-SSL-0.4.0.2@sha256:c33082ae7ce0ab6c5d77aa810f4404320e275a8f93cab3a8e47d21c01884113b,2061
- microlens-pro-0.2.0.4

flags:
  zip:
    disable-bzip2: true

system-ghc: true
nix:
  enable: false # We enter the shell manually.
with-hpack: hpack
