resolver: lts-16.12
packages:

- smos
- smos-data
- smos-data-gen
- smos-cursor
- smos-cursor-gen
- smos-report
- smos-report-gen
- smos-report-cursor
- smos-report-cursor-gen
- smos-query
- smos-single
- smos-scheduler
- smos-archive
- smos-convert-org
- smos-calendar-import
- smos-docs-site
- smos-api
- smos-api-gen
- smos-server
- smos-server-gen
- smos-client
- smos-shell
- smos-sync-client
- smos-sync-client-gen
- smos-web-style
- smos-web-server
- smos-notify
- smos-github

# These are duplicated in nix/overlay.
ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef -Wcompat

extra-deps:
- envparse-0.4.1@sha256:989902e6368532548f61de1fa245ad2b39176cddd8743b20071af519a709ce30,2842

- git: https://github.com/jtdaugherty/vty.git
  commit: 6a9c90da0e093cec1d4903924eb0f6a33be489cb

- github: ixmatus/orgmode-parse
  commit: 1bdfbfe8fb7299724a6f6a122a93b2e96dd839f8

# Calendar
- github: NorfairKing/iCalendar
  commit: 70c924ad6275ba05a514e31af1607a5b175f98ad

- mime-0.4.0.2@sha256:208947d9d1a19d08850be67ecb28c6e776db697f3bba05bd9d682e51a59f241f,983

- github: haskell-servant/servant-auth
  commit: 296de3cb69135f83f0f01169fc10f8b3a2539405
  subdirs:
    - servant-auth
    - servant-auth-client
    - servant-auth-docs
    - servant-auth-swagger
    - servant-auth-server

# Password
- github: cdepillabout/password 
  commit: e90b7481af2d63de6b2d9ead3c03ddb798707d22
  subdirs:
    - password
    - password-types
    - password-instances


- github: NorfairKing/typed-uuid
  commit: ec82b82a545d06094ac355bd65a03f25f86c0a48
  subdirs:
  - typed-uuid
  - genvalidity-typed-uuid

- github: GaloisInc/sqlite
  commit: e93ee84000c1d1eedbc23036c4a20ffd07e3145f

- github: NorfairKing/mergeful
  commit: b520f251010e80748c4eea1ba7216f2594c4f760
  subdirs:
    - mergeful
    - mergeful-persistent
    - genvalidity-mergeful
  
- github: NorfairKing/looper
  commit: 8946c243a718bd44089f50d4c0fb624fd1f7db2a
  subdirs:
    - looper
  
- github: NorfairKing/pretty-relative-time
  commit: 1c0ca0e24b2a5973e5ccf4e83d24097a22bb9a4a

- github: NorfairKing/cursor-fuzzy-time
  commit: e364adc5ed04e59321aecc9a6158ca3c16f5c0bf
  subdirs:
    - cursor-fuzzy-time
    - cursor-fuzzy-time-gen
  
- github: NorfairKing/fuzzy-time
  commit: 6ca085188fa71609bf1a72aaa3779f7d429392e0
  subdirs:
    - fuzzy-time
    - fuzzy-time-gen

- github: NorfairKing/dirforest
  commit: fa5bc20f28badff95efcb1e63e7fdec53b7bb1fe
  subdirs:
    - dirforest
    - genvalidity-dirforest

- github: NorfairKing/cursor-dirforest
  commit: 01e862938e7950b70d0c725dbe639f6a3d369e93
  subdirs:
    - cursor-dirforest
    - cursor-dirforest-gen
    - cursor-dirforest-brick

- github: NorfairKing/cursor-brick
  commit: 95345daf6a7036601bbaaf268d2a9ed7c713312b
  subdirs:
    - cursor-brick

- github: NorfairKing/cursor
  commit: 71ec3154809e229efbf35d500ac6d1a42ae5fdc0
  subdirs:
    - cursor
    - cursor-gen

- github: NorfairKing/yamlparse-applicative
  commit: 7a329d06ffa45595963cf98f34910887115eb471
  subdirs:
  - yamlparse-applicative

- github: NorfairKing/safe-coloured-text
  commit: d840dd7b0f13f4d0fd693c1dd93be33f9ee94605
  subdirs:
  - safe-coloured-text
  - safe-coloured-text-gen
  - safe-coloured-text-layout
  - safe-coloured-text-layout-gen
  - safe-coloured-text-terminfo

- github: NorfairKing/sydtest
  commit: aafd8e0c2e97143af950e2f9742c5e1bd167c77b
  subdirs:
    - sydtest
    - sydtest-aeson
    - sydtest-discover
    - sydtest-persistent-sqlite
    - sydtest-servant
    - sydtest-wai
    - sydtest-yesod

- github: NorfairKing/validity
  commit: 86a824729519c154c23f0757f2ce4b9ab93b675a
  subdirs:
    - genvalidity
    - genvalidity-aeson
    - genvalidity-bytestring
    - genvalidity-containers
    - genvalidity-criterion
    - genvalidity-hspec
    - genvalidity-hspec-aeson
    - genvalidity-hspec-binary
    - genvalidity-hspec-cereal
    - genvalidity-hspec-hashable
    - genvalidity-hspec-optics
    - genvalidity-hspec-persistent
    - genvalidity-path
    - genvalidity-persistent
    - genvalidity-property
    - genvalidity-scientific
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-sydtest-hashable
    - genvalidity-sydtest-lens
    - genvalidity-sydtest-persistent
    - genvalidity-text
    - genvalidity-time
    - genvalidity-unordered-containers
    - genvalidity-uuid
    - genvalidity-vector
    - validity
    - validity-aeson
    - validity-bytestring
    - validity-containers
    - validity-path
    - validity-persistent
    - validity-primitive
    - validity-scientific
    - validity-text
    - validity-time
    - validity-unordered-containers
    - validity-uuid
    - validity-vector



 
- github: NorfairKing/yesod-static-remote
  commit: f91fdbc2ac74cf8d005f536cfbbf9b4385cbbba6
- github: NorfairKing/yesod-autoreload
  commit: 2adfb0397ca82a81ee26e0e491fe8b2759d76615

- github: NorfairKing/haskeline
  commit: 7c6491c55741608255c2681702381ce488692d15

- github: NorfairKing/template-haskell-reload
  commit: 6f8627b45ae63f64ad0a47d1130630aa2e24470d
  subdirs:
    - template-haskell-reload

- github-0.26@sha256:a9d4046325c3eb28cdc7bef2c3f5bb213328caeae0b7dce6f51de655f0bffaa1,7162
- binary-instances-1.0.1@sha256:56bb2da1268415901d6ea3f46535b88b89459d7926fbfcca027e25e069ea6f2b,2647
- time-compat-1.9.5@sha256:f343bc5339a217ecef497e3a730017e15f5c396713fe1d653b8a9e7b1f666988,4932

flags:
  zip:
    disable-bzip2: true

nix:
  shell-file: shell.nix
  add-gc-roots: true
