name: smos-cli
version: 0.0.0
category: Smos
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
license: MIT

dependencies:
  base

library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
  - bytestring
  - monad-logger
  - password
  - text
