name: smos-sync-client
version: 0.6.0
category: Smos
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
license: MIT

dependencies:
- base

library:
  source-dirs: src/
  ghc-options: -Wall
  build-tools: autoexporter
  dependencies:
  - aeson
  - aeson-pretty
  - autodocodec
  - bytestring
  - containers
  - cookie
  - deepseq
  - dirforest
  - filelock
  - filepath
  - hostname
  - http-client
  - http-client-tls
  - http-types
  - mergeful
  - monad-logger
  - mtl
  - opt-env-conf
  - path
  - path-io
  - persistent
  - persistent-sqlite
  - pretty-show
  - servant-auth-client
  - servant-client
  - smos-api
  - smos-cli
  - smos-client
  - smos-directory
  - text
  - time
  - unix
  - unliftio
  - validity
  - validity-bytestring
  - validity-containers
  - validity-path
  - validity-uuid

executables:
  smos-sync-client:
    main: Main.hs
    source-dirs: app
    dependencies:
    - smos-sync-client
