name: smos-report-gen
version: 0.3.1
category: Smos
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
license: MIT

extra-source-files:
- test_resources/**/*

dependencies:
- base >=4.9 && <=5

  
library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
  - QuickCheck
  - bytestring
  - containers
  - cursor
  - cursor-gen
  - deepseq
  - dirforest
  - genvalidity >=1.0
  - genvalidity-bytestring
  - genvalidity-containers
  - genvalidity-dirforest
  - genvalidity-sydtest
  - genvalidity-path
  - genvalidity-text
  - genvalidity-time
  - path
  - path-io
  - smos-data
  - smos-data-gen
  - smos-report
  - text
  - time

tests:
  smos-report-test:
    main: Spec.hs
    source-dirs: test/
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - containers
    - cursor
    - cursor-gen
    - dirforest
    - genvalidity-containers
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-path
    - sydtest
    - megaparsec
    - parsec
    - path
    - path-io
    - smos-data
    - smos-data-gen
    - smos-report
    - smos-report
    - smos-report-gen
    - text
    - time


benchmarks:
  smos-report-bench:
    main: Main.hs
    source-dirs: bench/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - containers
    - criterion
    - cursor
    - genvalidity
    - genvalidity-containers
    - genvalidity-criterion
    - genvalidity-path
    - path
    - smos-data
    - smos-data-gen
    - smos-report
    - smos-report-gen
    - text
