name: smos-report-gen
version: 0.1.0
category: Smos
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
copyright: ! 'Copyright: (c) 2018-2020 Tom Sydney Kerckhove'
license: MIT
homepage: https://github.com/NorfairKing/smos

dependencies:
  - base >=4.9 && <=5
  
library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
  - QuickCheck
  - bytestring
  - containers
  - cursor
  - cursor-gen
  - deepseq
  - dirforest
  - genvalidity
  - genvalidity-bytestring
  - genvalidity-containers
  - genvalidity-dirforest
  - genvalidity-hspec
  - genvalidity-path
  - genvalidity-text
  - genvalidity-time
  - path
  - path-io
  - pretty-show
  - smos-data
  - smos-data-gen
  - smos-report
  - text
  - time

tests:
  smos-report-test:
    main: Spec.hs
    source-dirs: test/
    build-tools: hspec-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - containers
    - cursor
    - cursor-gen
    - dirforest
    - genvalidity-containers
    - genvalidity-hspec
    - genvalidity-hspec-aeson
    - genvalidity-path
    - hspec
    - megaparsec
    - parsec
    - path
    - path-io
    - pretty-show
    - smos-cursor
    - smos-cursor-gen
    - smos-data
    - smos-data-gen
    - smos-report
    - smos-report
    - smos-report-gen
    - text
    - time


benchmarks:
  smos-report-bench:
    main: Main.hs
    source-dirs: bench/
    ghc-options:
    - -Wall
    dependencies:
    - QuickCheck
    - containers
    - criterion
    - cursor
    - genvalidity
    - genvalidity-containers
    - genvalidity-criterion
    - genvalidity-path
    - path
    - smos-data
    - smos-data-gen
    - smos-report
    - smos-report-gen
    - text
