name: smos-web-server
version: 0.11.0
category: Smos
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
license: MIT

extra-source-files:
- routes.txt
- templates/**/*
- assets/**/*

dependencies:
- base

library:
  source-dirs: src/
  ghc-options: -Wall
  build-tools: autoexporter
  dependencies:
  - aeson
  - autodocodec
  - autodocodec-yaml
  - bytestring
  - conduit
  - containers
  - data-default
  - deepseq
  - envparse
  - http-client
  - http-client-tls
  - http-types
  - ical
  - monad-logger
  - mtl
  - optparse-applicative
  - path
  - path-io
  - persistent-sqlite
  - pretty-relative-time
  - pretty-show
  - servant
  - servant-auth-client
  - servant-client
  - shakespeare
  - smos
  - smos-cli
  - smos-client
  - smos-data
  - smos-directory
  - smos-e2e
  - smos-report
  - smos-sync-client
  - smos-web-style
  - template-haskell
  - text
  - time
  - typed-uuid
  - tz
  - unliftio
  - wai-extra
  - warp
  - yaml
  - yesod
  - yesod-auth
  - yesod-autoreload
  - yesod-static
  - yesod-static-remote
  - yesod-websockets

executables:
  smos-web-server:
    main: Main.hs
    source-dirs: app
    dependencies:
    - smos-web-server
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -optP-Wno-nonportable-include-path # For macos


tests:
  smos-web-server-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - genvalidity-sydtest
    - http-client
    - http-types
    - monad-logger
    - servant-client
    - smos-client
    - smos-data-gen
    - smos-server-gen
    - smos-web-server
    - smos-web-style
    - sydtest
    - sydtest-yesod
    - text
    - yesod-auth
