name: smos-web-server
version: 0.1.1
category: Smos
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
copyright: ! 'Copyright: (c) 2020 Tom Sydney Kerckhove'
license: MIT
homepage: https://github.com/NorfairKing/smos

extra-source-files:
- routes.txt
- templates/**/*

dependencies:
- base

library:
  source-dirs: src/
  ghc-options: -Wall
  build-tools: autoexporter
  dependencies:
  - aeson
  - aeson-pretty
  - async
  - base16-bytestring
  - bytestring
  - conduit
  - containers
  - cursor
  - data-default
  - dirforest
  - envparse
  - filepath
  - http-client
  - http-client-tls
  - http-types
  - monad-logger
  - optparse-applicative
  - path
  - path-io
  - persistent-sqlite
  - pretty-show
  - random
  - servant-auth-client
  - servant-client
  - shakespeare
  - smos
  - smos-client
  - smos-data
  - smos-report
  - smos-shell
  - smos-sync-client
  - smos-web-style
  - stm
  - template-haskell
  - text
  - unix
  - unliftio
  - wai
  - wai-extra
  - warp
  - yaml
  - yamlparse-applicative
  - yesod
  - yesod-auth
  - yesod-autoreload
  - yesod-static
  - yesod-static-remote
  - yesod-websockets

executables:
  smos-web-server:
    main: Main.hs
    source-dirs: app
    dependencies:
    - smos-web-server
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -optP-Wno-nonportable-include-path # For macos


tests:
  smos-web-server-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytestring
    - containers
    - genvalidity
    - genvalidity-sydtest
    - http-client
    - http-types
    - monad-logger
    - path
    - path-io
    - servant-client
    - smos-api-gen
    - smos-client
    - smos-data
    - smos-data-gen
    - smos-server-gen
    - smos-sync-client
    - smos-web-server
    - smos-web-style
    - stm
    - sydtest
    - sydtest-yesod
    - text
    - yesod-auth
