name: smos-notify
version: 0.4.0
category: Smos
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
license: MIT

data-files:
  - assets/ting.wav
  - assets/logo.png

dependencies:
- base

library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
    - autodocodec
    - conduit
    - containers
    - filepath
    - hashable
    - monad-logger
    - opt-env-conf
    - path
    - path-io
    - persistent
    - persistent-sqlite
    - pretty-relative-time
    - pretty-show
    - process
    - smos-cli
    - smos-data
    - smos-directory
    - text
    - time

executables:
  smos-notify:
    main: Main.hs
    source-dirs: app
    dependencies:
    - smos-notify
