name: smos-data
version: 0.5.0
category: Smos
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
license: MIT

library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
  - aeson
  - aeson-pretty
  - autodocodec
  - autodocodec-yaml
  - base
  - bytestring
  - containers
  - deepseq
  - microlens
  - path
  - path-io
  - semver
  - text
  - time
  - tz
  - unliftio
  - validity
  - validity-containers
  - validity-text
  - validity-time
  - yaml
