name: smos-client
version: 0.5.0
category: Smos
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
license: MIT

dependencies:
- base

library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
  - bytestring
  - cookie
  - deepseq
  - dirforest
  - http-types
  - microlens
  - path
  - pretty-show
  - semver
  - servant
  - servant-auth-client
  - servant-auth-server
  - servant-client
  - servant-client-core
  - smos-api
  - smos-data
  - smos-report
  - text
  - time

tests:
  smos-client-test:
    main: Spec.hs
    source-dirs: test/
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - smos-api
    - smos-client
    - smos-data
    - sydtest
