name: smos-server
version: 0.12.0
category: Smos
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
license: MIT


extra-source-files:
- templates/**/*

dependencies:
- base

library:
  source-dirs: src/
  ghc-options: -Wall
  build-tools: autoexporter
  dependencies:
  - IntervalMap
  - aeson
  - aeson-pretty
  - amazonka
  - amazonka-ses
  - autodocodec
  - autodocodec-yaml
  - blaze-html
  - bytestring
  - conduit
  - containers
  - dirforest
  - envparse
  - filepath
  - http-client
  - http-types
  - ical
  - jose
  - looper
  - mergeful
  - microlens
  - mime-mail
  - monad-logger
  - mtl
  - network-uri
  - optparse-applicative
  - path
  - path-io
  - persistent
  - persistent-pagination
  - persistent-sqlite
  - pretty-show
  - retry
  - semver
  - servant
  - servant-auth-server
  - servant-server
  - shakespeare
  - smos-api
  - smos-cli
  - smos-data
  - smos-directory
  - smos-report
  - smos-stripe-client
  - template-haskell
  - text
  - time
  - typed-uuid
  - tz
  - unliftio
  - unliftio
  - validity
  - validity-persistent
  - wai
  - wai-extra
  - warp
  - yaml
  - zip
  - zstd

executables:
  smos-server:
    main: Main.hs
    source-dirs: app
    dependencies:
    - smos-server
