name: smos-query
version: 0.9.0
category: Smos
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
license: MIT

dependencies:
  base

library:
  source-dirs: src/
  ghc-options: -Wall
  build-tools: autoexporter
  dependencies:
  - IntervalMap
  - aeson
  - aeson-pretty
  - autodocodec
  - bytestring
  - conduit
  - containers
  - envparse
  - mtl
  - optparse-applicative
  - path
  - pretty-relative-time
  - safe-coloured-text
  - safe-coloured-text-terminfo
  - smos-cli
  - smos-data
  - smos-directory
  - smos-report
  - text
  - time
  - tz
  - validity
  - validity-path
  - yaml

executables:
  smos-query:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - smos-query

tests:
  smos-query-test:
    main: Spec.hs
    source-dirs: test/
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - containers
    - genvalidity-sydtest
    - path
    - path-io
    - smos-query
    - smos-report
    - smos-directory-gen
    - sydtest
    - text
    - yaml
