name: smos-data-gen
version: 0.4.1
category: Smos
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
license: MIT

extra-source-files:
- test_resources/**/*

dependencies:
- base >=4.9 && <=5
  
library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
  - QuickCheck
  - genvalidity >=1.0
  - genvalidity-containers
  - genvalidity-text
  - genvalidity-time
  - path-io
  - containers
  - smos-data
  - sydtest
  - text
  - time
  - tz

tests:
  smos-data-test:
    main: Spec.hs
    source-dirs: test/
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - aeson
    - autodocodec
    - autodocodec-yaml
    - bytestring
    - containers
    - filepath
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - path
    - path-io
    - semver
    - smos-data
    - smos-data-gen
    - sydtest
    - text
    - time

benchmarks:
  smos-data-bench:
    main: Main.hs
    source-dirs: bench/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - containers
    - criterion
    - genvalidity-containers
    - genvalidity-criterion
    - path
    - path-io
    - smos-data
    - smos-data-gen
