name: smos
version: 0.9.0
category: Smos
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
license: MIT

library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
  - aeson
  - async
  - autodocodec
  - base
  - brick
  - bytestring
  - conduit
  - containers
  - cursor
  - cursor-brick
  - cursor-dirforest
  - cursor-dirforest-brick
  - cursor-fuzzy-time
  - directory
  - envparse
  - exceptions
  - filepath
  - fuzzy-time
  - megaparsec
  - microlens
  - monad-logger
  - mtl
  - optparse-applicative
  - path
  - path-io
  - pretty-relative-time
  - process
  - resourcet
  - smos-archive
  - smos-cli
  - smos-cursor
  - smos-data
  - smos-directory
  - smos-report
  - smos-report-cursor
  - text
  - time
  - tz
  - validity
  - vty
  - vty-crossplatform


executables:
  smos:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N # Use up to as many cores as are available
    - -with-rtsopts=-I0 # No idle GC
    - -optP-Wno-nonportable-include-path # For macos
    dependencies:
    - base
    - smos

tests:
  smos-test:
    main: Main.hs
    source-dirs: test/
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - base
    - bytestring
    - containers
    - genvalidity
    - genvalidity-containers
    - genvalidity-path
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-text
    - genvalidity-time
    - genvalidity-unordered-containers
    - megaparsec
    - path
    - path-io
    - resourcet
    - smos
    - smos-cursor-gen
    - smos-data
    - smos-data-gen
    - smos-report-gen
    - sydtest
    - text
    - vty
