name: smos-cursor
version: 0.6.0
github: NorfairKing/smos
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu

library:
  source-dirs: src
  dependencies:
  - base
  - containers
  - cursor
  - cursor-dirforest
  - cursor-fuzzy-time
  - deepseq
  - dirforest
  - exceptions
  - filelock
  - fuzzy-time
  - microlens
  - path
  - path-io
  - resourcet
  - smos-archive
  - smos-data
  - text
  - time
  - tz
  - validity
  - validity-time
