name: smos-directory
version: 0.1.0
category: Smos
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
license: MIT

dependencies:
- base

library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
  - autodocodec
  - conduit
  - containers
  - cursor
  - envparse
  - microlens
  - opt-env-conf
  - optparse-applicative
  - path
  - path-io
  - smos-data
  - validity
  - validity-path
