name: smos-server-gen
version: 0.7.0
category: Smos
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
license: MIT

extra-source-files:
- test_resources/**/*

dependencies:
- base

library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
  - bytestring
  - containers
  - deepseq
  - dirforest
  - genvalidity
  - genvalidity-persistent
  - genvalidity-time
  - genvalidity-typed-uuid
  - http-client
  - mergeful
  - path
  - persistent-sqlite
  - servant-auth-client
  - servant-auth-server
  - smos-api-gen
  - smos-client
  - smos-data
  - smos-data-gen
  - smos-directory-gen
  - smos-server
  - smos-sync-client
  - sydtest
  - sydtest-persistent-sqlite
  - sydtest-wai
  - unliftio

tests:
  smos-server-test:
    main: Spec.hs
    source-dirs: test/
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - bytestring
    - containers
    - dirforest
    - genvalidity-bytestring
    - genvalidity-persistent
    - genvalidity-sydtest
    - http-types
    - mergeful
    - mtl
    - path
    - path-io
    - persistent
    - servant
    - servant-client
    - smos-api
    - smos-client
    - smos-data
    - smos-data-gen
    - smos-directory-gen
    - smos-report
    - smos-server
    - smos-server-gen
    - sydtest
    - sydtest-persistent-sqlite
    - time
    - typed-uuid
    - zip
    - zstd

executables:
  smos-server-end-to-end-test:
    main: Main.hs
    source-dirs: app/
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - http-client-tls
    - http-types
    - mtl
    - semver
    - servant-client
    - smos-client
    - smos-data
    - sydtest
    - text
