name: smos-report-cursor
version: 0.3.0
category: Smos
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
license: MIT

library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
  - base
  - conduit
  - containers
  - cursor
  - deepseq
  - microlens
  - path
  - smos-cursor
  - smos-data
  - smos-report
  - time
  - validity
  - validity-path
