name: smos-docs-site
version: 0.1.0
github: "NorfairKing/smos"
license: MIT
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "2018-2020 Tom Sydney Kerckhove"

extra-source-files:
- routes
- content/**
- templates/**/*

library:
  source-dirs: src
  build-tools: autoexporter
  dependencies:
  - base >= 4.7
  - cmark-gfm
  - containers
  - data-default
  - envparse
  - filepath
  - fsnotify
  - optparse-applicative
  - path
  - path-io
  - raw-strings-qq
  - semver
  - shakespeare
  - smos
  - smos-archive
  - smos-calendar-import
  - smos-client
  - smos-data
  - smos-github
  - smos-notify
  - smos-query
  - smos-report
  - smos-scheduler
  - smos-server
  - smos-single
  - smos-sync-client
  - smos-web-server
  - smos-web-style
  - template-haskell
  - template-haskell-reload
  - text
  - th-lift-instances
  - time
  - typed-process
  - wai-extra
  - warp
  - yaml
  - yamlparse-applicative
  - yesod
  - yesod-autoreload
  - yesod-sitemap
  - yesod-static
  - yesod-static-remote

executables:
  smos-docs-site:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - smos-docs-site
