name: smos-docs-site
version: 0.0.0
github: NorfairKing/smos
license: MIT
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu

extra-source-files:
- routes
- content/assets/**/*
- content/casts/**/*.yaml
- content/changelogs/**/*
- content/pages/**/*
- content/unreleased.markdown
- templates/**/*

library:
  source-dirs: src
  build-tools: autoexporter
  dependencies:
  - aeson
  - autodocodec
  - autodocodec-yaml
  - base >= 4.7
  - bytestring
  - cmark-gfm
  - containers
  - data-default
  - envparse
  - file-embed
  - filepath
  - fsnotify
  - optparse-applicative
  - path
  - path-io
  - raw-strings-qq
  - semver
  - shakespeare
  - smos
  - smos-archive
  - smos-calendar-import
  - smos-cli
  - smos-client
  - smos-data
  - smos-github
  - smos-jobhunt
  - smos-notify
  - smos-query
  - smos-report
  - smos-scheduler
  - smos-server
  - smos-single
  - smos-sync-client
  - smos-web-server
  - smos-web-style
  - template-haskell
  - template-haskell-reload
  - text
  - th-lift-instances
  - time
  - typed-process
  - wai-extra
  - warp
  - yaml
  - yesod
  - yesod-autoreload
  - yesod-sitemap
  - yesod-static
  - yesod-static-remote

executables:
  smos-docs-site:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - smos-docs-site
