name: smos-docs-site
version: 0.0.0
github: NorfairKing/smos
license: MIT
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu

extra-source-files:
- routes
- content/assets/**/*
- content/casts/**/*.yaml
- content/changelogs/**/*
- content/pages/**/*
- content/unreleased.markdown
- templates/**/*
- documentation.txt
- options.nix

dependencies:
  - base

library:
  source-dirs: src
  build-tools: autoexporter
  dependencies:
  - aeson
  - autodocodec
  - autodocodec-yaml
  - bytestring
  - cmark-gfm
  - containers
  - data-default
  - file-embed
  - filepath
  - fsnotify
  - opt-env-conf
  - path
  - path-io
  - raw-strings-qq
  - safe-coloured-text
  - semver
  - shakespeare
  - smos
  - smos-archive
  - smos-calendar-import
  - smos-client
  - smos-data
  - smos-github
  - smos-jobhunt
  - smos-notify
  - smos-query
  - smos-report
  - smos-scheduler
  - smos-server
  - smos-single
  - smos-sync-client
  - smos-web-assets
  - smos-web-server
  - template-haskell
  - template-haskell-reload
  - text
  - time
  - wai-extra
  - warp
  - yaml
  - yesod
  - yesod-autoreload
  - yesod-sitemap
  - yesod-static
  - yesod-static-remote

executables:
  smos-docs-site:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - smos-docs-site

tests:
  smos-docs-site-test:
    main: Spec.hs
    source-dirs: test/
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - opt-env-conf-test
    - smos-docs-site
    - sydtest
