name: smos-cursor-gen
version: 0.2.0
github: NorfairKing/smos
author: Tom Sydney Kerckhove
maintainer: sydcs-syd.eu

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - QuickCheck
  - base
  - cursor
  - cursor-dirforest
  - cursor-dirforest-gen
  - cursor-fuzzy-time-gen
  - cursor-gen
  - genvalidity >=1.0
  - genvalidity-path
  - genvalidity-text
  - smos-cursor
  - smos-data
  - smos-data-gen

tests:
  smos-cursor-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - bytestring
    - cursor
    - cursor-dirforest
    - cursor-fuzzy-time-gen
    - cursor-gen
    - dirforest
    - genvalidity-sydtest
    - genvalidity-sydtest-lens
    - genvalidity-path
    - sydtest
    - path
    - path-io
    - resourcet
    - smos-cursor
    - smos-cursor-gen
    - smos-data
    - smos-data-gen

benchmarks:
  smos-cursor-bench:
    main: Bench.hs
    source-dirs: bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - criterion
    - cursor
    - cursor-fuzzy-time-gen
    - genvalidity-criterion
    - smos-cursor
    - smos-cursor-gen
    - smos-data
    - smos-data-gen
