name: NixCI Oneshot
on: [push, pull_request, release]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - uses: cachix/cachix-action@v12
      with:
        name: nix-ci

    - run: nix run github:NorfairKing/nix-ci#github-actions-worker
      env:
        NIX_CI_WORKER_NAME: 'github-action'
        NIX_CI_WORKER_PRIVATE_KEY: '${{ secrets.NIX_CI_WORKER_PRIVATE_KEY }}'
        NIX_CI_WORKER_LEADER: https://api.staging.nix-ci.com
