name: smos-sync-client-gen
version: 0.4.1
category: Smos
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
license: MIT

extra-source-files:
- test_resources/**/*

dependencies:
- base

library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
  - QuickCheck
  - async
  - bytestring
  - containers
  - dirforest
  - genvalidity >=1.0
  - genvalidity-dirforest
  - genvalidity-sydtest
  - monad-logger
  - path
  - path-io
  - persistent-sqlite
  - servant-client
  - smos-api
  - smos-api-gen
  - smos-sync-client
  - sydtest
  - sydtest-persistent-sqlite

tests:
  smos-sync-client-test:
    main: Spec.hs
    source-dirs: test/
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - bytestring
    - containers
    - genvalidity-bytestring
    - genvalidity-path
    - genvalidity-sydtest
    - jose
    - mergeful
    - monad-logger
    - path
    - path-io
    - persistent-sqlite
    - resource-pool
    - servant-auth-server
    - servant-client
    - smos-api
    - smos-api-gen
    - smos-server
    - smos-server-gen
    - smos-sync-client
    - smos-sync-client-gen
    - sydtest
    - sydtest-persistent-sqlite
    - sydtest-wai
    - text

benchmarks:
  smos-sync-client-bench:
    main: Bench.hs
    source-dirs: bench/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - criterion
    - genvalidity-criterion
    - smos-sync-client
    - smos-sync-client-gen
